### PR TITLE
Applied skeletal implementation to interface migration automated refactoring

### PR DESCRIPTION
**Pull request by khatchad**
This is a semantics-preserving automated refactoring that migrates existing method implementations in classes to the corresponding implemented interface methods as `default` methods. The tool **does not** add new code; it only rearranges *existing* code.

- We are evaluating a research prototype automated refactoring Eclipse plug-in called [Migrate Skeletal Implementation to Interface](https://github.com/khatchad/Migrate-Skeletal-Implementation-to-Interface-Refactoring). We have applied the tool to your project in the hopes of receiving feedback.
- The approach is very conservative. That may mean that not all changes that can be made were made. Please feel free to continue the refactoring manually if you wish.
- We migrated methods declared in both abstract and concrete classes with the hopes of such methods being suitable default methods in corresponding interfaces.
- The source code should be semantically equivalent to the original.
- There was one manual change reversal due to an implementation stemming from a unit test that was too test specific.

Thank you for your help in this evaluation! Any feedback you can provide would be very helpful. In particular, we are interested if *each* of the proposed changes are helpful or not.

### CODE REVIEW

**Comment by khatchad** [comment]
Looks like this pull request if failing on a deploy operation.

**Comment by andrus** [comment]
Thanks for the PR. You are right about CI failure being due to the deploy command (hmm, how do we instruct travis to not deploy PR builds?). Some good refactoring ideas in the PR. Will still require manual intervention. Specifically 2 constants in ```DefaultEnvironment``` (FRAMEWORK_PROPERTIES_PREFIX, FRAMEWORK_VARIABLES_PREFIX) should be moved to the interface with deprecation in the class. 

I might do just that.

**Comment by khatchad** [comment]
@andrus Thank you for the feedback! I'm not sure if I can help with the deployment issue, but I did file an issue https://github.com/khatchad/Migrate-Skeletal-Implementation-to-Interface-Refactoring/issues/167 to automate your suggestion. I'll have a look at it as well.

**Comment by andrus** [comment]
> I'm not sure if I can help with the deployment issue

Don't worry about this one. We'll figure it out.

**Comment by khatchad** [comment]
@andrus Sounds good. In e939d8c760a1a1f68d9f8ea33c806875e947f055, I've made the semi-manual change that you suggested. Please let me know if there is any other feedback and thank you again for your consideration!

**Comment by andrus** [comment]
Merged. As an automated refactoring fix does not require an ICLA

**Comment by khatchad** [comment]
Thank you!

**Pull request merged**
