### PR TITLE
Support for MS Windows

### PR DESCRIPTION
**Pull request by atomashpolskiy**
@andrus , fixed one failing test

### CODE REVIEW

**Comment by atomashpolskiy** [comment]
commit bf4a27e:
this is a fix for the case when user.dir is windows-style `Z:\a\b\c`, and ResourceFactory tries to build a URI from its string representation (passed from FolderResourceFactory), resulting in a URI constructor treating drive letter `Z:` as scheme and generating a `URISyntaxException`

**Comment by andrus** [comment]
This is related to #73

**Comment by andrus** [comment]
@atomashpolskiy : path to "file:" URL conversion is only applied to "user.dir". What if constructor parameter is "z:\a\b\c"?

**Comment by atomashpolskiy** [comment]
@andrus , are such resource IDs allowed? For some reason I assumed that resource IDs should be abstract URIs (absolute or relative unix-style pathes in case of resources located on the filesystem, i.e. /a/b/c in your case). Am I being wrong here?

**Comment by atomashpolskiy** [comment]
Or file://Z:/a/b/c of course (i.e. a URI)

**Comment by andrus** [comment]
I guess you are right - resource paths should be platform-independent and use forward slashes. Still will need to test paths like ```z:/a/b/c``` I guess. In that case we should not call "slashify" inside ```normalizeResourceId```.

**Comment by atomashpolskiy** [comment]
Removed slashify, added tests

**Comment by andrus** [comment]
1. We still need conditional unit tests for ```file:///Z:/a/b/c```
2. I think ```FolderResourceFactory.getUserDir()``` shouldn't be public.

**Comment by atomashpolskiy** [comment]
@andrus , done. Instead of a conditional test I added a platform-independent test for both `file:/Z:/a/b/c` and `file:///Z:/a/b/c` cases

**Pull request merged**
